### ISSUE TITLE
Flash plugin outdated warnings in firefox

### ISSUE THREAD

**Issue by gjanssens** [negativo17/flash-plugin#1]
Hi,

For some time now firefox (on my Fedora 23 system) complains that the installed flash plugin is outdated and I should install a more recent version. I have installed the flash-plugin from this repo. The current version in the repo is flash-plugin-11.2.202.621-1.fc23.x86_64.
However Adobe has moved on to version 11.2.202.626.

Can you provide an updated package ?
Thank you for your work!

**Comment by scaronni** [comment]
Thanks for notifying, i checked two days ago and there was no new updated. Uploading now.
