### ISSUE TITLE
flash-plugin el7 update or libstdc++  issue?

### ISSUE THREAD

**Issue by pjwelsh** [negativo17/flash-plugin#2]
yum list updates
...
flash-plugin.x86_64                     1:32.0.0.293-1.el7                      epel-multimedia

yum update
...
---> Package flash-plugin.x86_64 1:32.0.0.293-1.el7 will be an update
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.21)(64bit) for package: 1:flash-plugin-32.0.0.293-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: 1:flash-plugin-32.0.0.293-1.el7.x86_64 (epel-multimedia)
           Requires: libstdc++.so.6(GLIBCXX_3.4.21)(64bit)

**Comment by scaronni** [comment]
Ok, it seems this goes along with UniFi Controller and Spotify in the list of software that no longer runs on RHEL 7. I will revert the update.

**Comment by pjwelsh** [comment]
Just as a note, the "official" flash-player-npapi-32.0.0.293 does not have this issue.
Even more odd is that the flash-plugin-32.0.0.293-1.el7.x86_64 did update "normally" on at least one CentOS 7 system that does not seem have the libstdc++.so.6(GLIBCXX_3.4.21) installed.

I did do a yumdownloader to see if I had gotten some a different flash-plugin*.rpm, but it was the same:
$ rpm -qp --requires flash-plugin-32.0.0.293-1.el7.x86_64.rpm|grep libstdc++
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.21)(64bit)

The install on the system in question was not forced or anything:
$ rpm -q --requires flash-plugin-32.0.0.293-1.el7.x86_64|grep libstdc++
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.21)(64bit)

I do have some "extra" packages like "emby-server" on that system that could allow that GLIBCXX_3.4.21 version:
$ strings /opt/emby-server/lib/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
...
GLIBCXX_3.4.21
GLIBCXX_3.4.22
...

$ yum -q provides */libstdc++.so.6.0.2*
Repository cr is listed more than once in the configuration
microsoft-mlserver-python-9.4.7-9.4.7.1025-1.x86_64 : Microsoft Machine Learning Server
Repo        : packages-microsoft-com-prod
Matched from:
Filename    : /opt/microsoft/mlserver/9.4.7/runtime/python/x86_64-conda_cos6-linux-gnu/sysroot/lib/libstdc++.so.6.0.25
Filename    : /opt/microsoft/mlserver/9.4.7/runtime/python/lib/libstdc++.so.6.0.25
Filename    : /opt/microsoft/mlserver/9.4.7/runtime/python/pkgs/libstdcxx-ng-8.2.0-hdf63c60_1/x86_64-conda_cos6-linux-gnu/sysroot/lib/libstdc++.so.6.0.25
Filename    : /opt/microsoft/mlserver/9.4.7/runtime/python/pkgs/libstdcxx-ng-8.2.0-hdf63c60_1/lib/libstdc++.so.6.0.25

emby-server-4.0.1.0-1.x86_64 : Emby Server is a personal media server with apps on just about
                             : every device.
Repo        : @/emby-server-rpm_4.0.1.0_x86_64
Matched from:
Filename    : /opt/emby-server/lib/libstdc++.so.6.0.22


Maybe these recent update builds are grabbing a wrong libstdc++.so.6 path compared to a "normal" install?

**Comment by scaronni** [comment]
The Microsoft packages should filter out libraries, if not, that's a but on their side.

Anyway the new Flash Plugin releases have restored the dependencies to something usable by older RHEL/CentOS releases.
